namespace: dev

replicaCount: 2
strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
image:
  repository: nginx
  tag: "1.22.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources: {}
